// Generated by scripts/train_chords.py from the mapped corpus (5580 beats, 18 tracks).
// Chord emission: score(root r, quality q) = w_q . rot(x, r) + b_q, where x is
// the L2-normalised beat chroma followed by the neighbouring beats' mean chroma rotated so r is pitch class 0.
#pragma once
#define CHORD_MODEL_DIM 24
#define CHORD_MODEL_CONTEXT 1
static const float CHORD_MODEL_W[2][24] = {
  { 5.0598f, -1.6120f, -0.9264f, -1.3713f, 1.2384f, -1.7080f, -0.6285f, 3.1141f, -1.8969f, -0.7722f, -0.5031f, 0.3978f, 3.9397f, -1.9579f, -0.0943f, -1.8920f, 0.5484f, -0.9240f, -0.8239f, 3.2379f, -2.1326f, -0.6638f, -0.3545f, 0.1813f },
  { 3.1931f, -0.6527f, -0.1028f, 0.8766f, -1.3981f, -1.7566f, -0.6940f, 2.6519f, -0.7209f, -0.8405f, -0.2178f, -0.7298f, 2.7248f, -0.4872f, 0.2485f, 0.9484f, -1.3160f, -1.1430f, -0.6171f, 2.3814f, -0.5142f, -0.6311f, -0.0523f, -0.6064f } };
static const float CHORD_MODEL_B[2] = { 0.2289f, -0.2289f };
