#!/usr/bin/env python3
"""Turn icon.png into the forms the app needs.

  --cpp PATH       write a C++ source embedding a 256x256 straight-RGBA copy
  --iconset DIR    write a macOS .iconset directory (feed to iconutil)

The source art is a rounded tile on a flat white background.  Everything
white that touches the border is made transparent and the tile is re-centred
with Apple's standard margin, so it matches other app icons in size and shape.
"""
import argparse, os, sys
from PIL import Image, ImageDraw

def load_tile(path):
    im = Image.open(path).convert("RGBA")
    w, h = im.size
    # Flood the background from all four corners with a tolerance wide enough
    # to eat antialiasing fringe but not the tile's own light strokes.
    for pt in [(0, 0), (w - 1, 0), (0, h - 1), (w - 1, h - 1)]:
        ImageDraw.floodfill(im, pt, (0, 0, 0, 0), thresh=40)
    bbox = im.getbbox()   # bbox of non-zero pixels (alpha now 0 outside)
    im = im.crop(bbox)
    # Centre it on a transparent square canvas with Apple's standard inset:
    # the tile spans 824 of a 1024 canvas, so it sits at the same size as
    # every other app icon in the Dock and Cmd-Tab.
    tile = max(im.size)
    side = round(tile * 1024 / 824)
    sq = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    sq.paste(im, ((side - im.width) // 2, (side - im.height) // 2))
    return sq

def write_cpp(tile, path, size=256):
    im = tile.resize((size, size), Image.LANCZOS)
    data = im.tobytes()   # straight (unpremultiplied) RGBA, row-major
    with open(path, "w") as f:
        f.write("// Generated by scripts/make-icon.py from icon.png -- do not edit.\n")
        f.write("#include \"icon_data.h\"\n\n")
        f.write(f"const int ICON_W = {size};\nconst int ICON_H = {size};\n")
        f.write("const unsigned char ICON_RGBA[] = {\n")
        for i in range(0, len(data), 32):
            f.write(",".join(str(x) for x in data[i:i + 32]) + ",\n")
        f.write("};\n")
    print(f"{path}: {size}x{size}, {len(data)} bytes")

ICONSET_SIZES = [16, 32, 128, 256, 512]

def write_iconset(tile, d):
    os.makedirs(d, exist_ok=True)
    for s in ICONSET_SIZES:
        tile.resize((s, s), Image.LANCZOS).save(f"{d}/icon_{s}x{s}.png")
        tile.resize((2 * s, 2 * s), Image.LANCZOS).save(f"{d}/icon_{s}x{s}@2x.png")
    print(f"{d}: {2 * len(ICONSET_SIZES)} images")

if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--src", default="icon.png")
    ap.add_argument("--cpp")
    ap.add_argument("--iconset")
    a = ap.parse_args()
    if not a.cpp and not a.iconset:
        ap.error("nothing to do: give --cpp and/or --iconset")
    tile = load_tile(a.src)
    if a.cpp: write_cpp(tile, a.cpp)
    if a.iconset: write_iconset(tile, a.iconset)
